force-app/main/default/objects/Case/fields/FS_AgenteQA__c.field-meta.xml
<CustomField>
    <fullName>FS_AgenteQA__c</fullName>
    <label>Agente QA</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_DescripcionCliente__c.field-meta.xml
<CustomField>
    <fullName>FS_DescripcionCliente__c</fullName>
    <label>Descripción Cliente</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Modulo__c.field-meta.xml
<CustomField>
    <fullName>FS_Modulo__c</fullName>
    <label>Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Producto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Núcleo del Sistema</fullName>
            </value>
            <value>
                <fullName>Cajas y Bóveda (Módulo 3)</fullName>
            </value>
            <value>
                <fullName>Captaciones a la Vista (Módulo 4)</fullName>
            </value>
            <value>
                <fullName>Captaciones a Plazo (Módulo 5)</fullName>
            </value>
            <value>
                <fullName>Colocaciones (Módulo 6)</fullName>
            </value>
            <value>
                <fullName>Comercio Exterior (Módulo 10)</fullName>
            </value>
            <value>
                <fullName>Tesorería (Módulo 12)</fullName>
            </value>
            <value>
                <fullName>Tarjeta de Débito (Módulo 15)</fullName>
            </value>
            <value>
                <fullName>DIPS (Modulo 19)</fullName>
            </value>
            <value>
                <fullName>Contabilidad (Módulo 20)</fullName>
            </value>
            <value>
                <fullName>Reportes (Módulo 21)</fullName>
            </value>
            <value>
                <fullName>Garantías (Módulo 28)</fullName>
            </value>
            <value>
                <fullName>Calendarizador Procesos Bach</fullName>
            </value>
            <value>
                <fullName>Core Tarjeta de Crédito</fullName>
            </value>
            <value>
                <fullName>MCM (MultiChannel Managemt)</fullName>
            </value>
            <value>
                <fullName>Business Application Generator</fullName>
            </value>
            <value>
                <fullName>Business Support Aplication</fullName>
            </value>
            <value>
                <fullName>BRE (Motor de reglas)</fullName>
            </value>
            <value>
                <fullName>Business Application Products (Plataforma de Ventas)</fullName>
            </value>
            <value>
                <fullName>BackOffice</fullName>
            </value>
            <value>
                <fullName>Online Banking Personas</fullName>
            </value>
            <value>
                <fullName>Mobile Banking Personas</fullName>
            </value>
            <value>
                <fullName>Kioskos</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Rapid Cash</fullName>
            </value>
            <value>
                <fullName>DIPS</fullName>
            </value>
            <value>
                <fullName>ECCO</fullName>
            </value>
            <value>
                <fullName>IMS</fullName>
            </value>
            <value>
                <fullName>Flujos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA CreditCard</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
            <value>
                <fullName>FISA FISS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SubModulo__c.field-meta.xml
<CustomField>
    <fullName>FS_SubModulo__c</fullName>
    <label>Sub Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Modulo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clientes (Módulo 2)</fullName>
            </value>
            <value>
                <fullName>Parametros Generales (Módulo 1)</fullName>
            </value>
            <value>
                <fullName>Seguridades (Modulo 90)</fullName>
            </value>
            <value>
                <fullName>Cuentas de Ahorro</fullName>
            </value>
            <value>
                <fullName>Cuentas Corrientes</fullName>
            </value>
            <value>
                <fullName>Cuentas de Acumulación</fullName>
            </value>
            <value>
                <fullName>Cuentas Nostro</fullName>
            </value>
            <value>
                <fullName>Cuentas Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Depositos a Plazo Fijo</fullName>
            </value>
            <value>
                <fullName>Créditos de Consumo/Comerciales/Personales</fullName>
            </value>
            <value>
                <fullName>Crédito Automotriz</fullName>
            </value>
            <value>
                <fullName>Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario con Letras</fullName>
            </value>
            <value>
                <fullName>Cartas de crédito</fullName>
            </value>
            <value>
                <fullName>Cobranzas</fullName>
            </value>
            <value>
                <fullName>Avales</fullName>
            </value>
            <value>
                <fullName>Boletas de garantía</fullName>
            </value>
            <value>
                <fullName>Títulos y valores</fullName>
            </value>
            <value>
                <fullName>Cupones</fullName>
            </value>
            <value>
                <fullName>Tarjetas Nominadas</fullName>
            </value>
            <value>
                <fullName>Tarjetas Innominadas</fullName>
            </value>
            <value>
                <fullName>Calendarización Y Procesos Masivos</fullName>
            </value>
            <value>
                <fullName>Administración multicanal</fullName>
            </value>
            <value>
                <fullName>Documentos</fullName>
            </value>
            <value>
                <fullName>Autorizaciones</fullName>
            </value>
            <value>
                <fullName>Seguridad</fullName>
            </value>
            <value>
                <fullName>Notificaciones</fullName>
            </value>
            <value>
                <fullName>Componente generales</fullName>
            </value>
            <value>
                <fullName>Herramientas de Desarrollo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_TipoIncidente__c.field-meta.xml
<CustomField>
    <fullName>FS_TipoIncidente__c</fullName>
    <label>Tipo de Incidente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Puntual</fullName>
            </value>
            <value>
                <fullName>Definitivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/FS_ProductoAdquirido__c.object-meta.xml
<CustomObject>
    <label>Producto Adquirido</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Nombre de Categoría</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos Adquiridos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>FS_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos Adquiridos</relationshipLabel>
    <relationshipName>ProductosAdquiridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Esta_activo__c.field-meta.xml
<CustomField>
    <fullName>FS_Esta_activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Está activo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Modulo__c.field-meta.xml
<CustomField>
    <fullName>FS_Modulo__c</fullName>
    <label>Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Producto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Núcleo del Sistema</fullName>
            </value>
            <value>
                <fullName>Cajas y Bóveda (Módulo 3)</fullName>
            </value>
            <value>
                <fullName>Captaciones a la Vista (Módulo 4)</fullName>
            </value>
            <value>
                <fullName>Captaciones a Plazo (Módulo 5)</fullName>
            </value>
            <value>
                <fullName>Colocaciones (Módulo 6)</fullName>
            </value>
            <value>
                <fullName>Comercio Exterior (Módulo 10)</fullName>
            </value>
            <value>
                <fullName>Tesorería (Módulo 12)</fullName>
            </value>
            <value>
                <fullName>Tarjeta de Débito (Módulo 15)</fullName>
            </value>
            <value>
                <fullName>DIPS (Modulo 19)</fullName>
            </value>
            <value>
                <fullName>Contabilidad (Módulo 20)</fullName>
            </value>
            <value>
                <fullName>Reportes (Módulo 21)</fullName>
            </value>
            <value>
                <fullName>Garantías (Módulo 28)</fullName>
            </value>
            <value>
                <fullName>Calendarizador Procesos Bach</fullName>
            </value>
            <value>
                <fullName>Core Tarjeta de Crédito</fullName>
            </value>
            <value>
                <fullName>MCM (MultiChannel Managemt)</fullName>
            </value>
            <value>
                <fullName>Business Application Generator</fullName>
            </value>
            <value>
                <fullName>Business Support Aplication</fullName>
            </value>
            <value>
                <fullName>BRE (Motor de reglas)</fullName>
            </value>
            <value>
                <fullName>Business Application Products (Plataforma de Ventas)</fullName>
            </value>
            <value>
                <fullName>BackOffice</fullName>
            </value>
            <value>
                <fullName>Online Banking Personas</fullName>
            </value>
            <value>
                <fullName>Mobile Banking Personas</fullName>
            </value>
            <value>
                <fullName>Kioskos</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Rapid Cash</fullName>
            </value>
            <value>
                <fullName>DIPS</fullName>
            </value>
            <value>
                <fullName>ECCO</fullName>
            </value>
            <value>
                <fullName>IMS</fullName>
            </value>
            <value>
                <fullName>Flujos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA CreditCard</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
            <value>
                <fullName>FISA FISS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_SubModulo__c.field-meta.xml
<CustomField>
    <fullName>FS_SubModulo__c</fullName>
    <label>Sub Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Modulo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clientes (Módulo 2)</fullName>
            </value>
            <value>
                <fullName>Parametros Generales (Módulo 1)</fullName>
            </value>
            <value>
                <fullName>Seguridades (Modulo 90)</fullName>
            </value>
            <value>
                <fullName>Cuentas de Ahorro</fullName>
            </value>
            <value>
                <fullName>Cuentas Corrientes</fullName>
            </value>
            <value>
                <fullName>Cuentas de Acumulación</fullName>
            </value>
            <value>
                <fullName>Cuentas Nostro</fullName>
            </value>
            <value>
                <fullName>Cuentas Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Depositos a Plazo Fijo</fullName>
            </value>
            <value>
                <fullName>Créditos de Consumo/Comerciales/Personales</fullName>
            </value>
            <value>
                <fullName>Crédito Automotriz</fullName>
            </value>
            <value>
                <fullName>Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario con Letras</fullName>
            </value>
            <value>
                <fullName>Cartas de crédito</fullName>
            </value>
            <value>
                <fullName>Cobranzas</fullName>
            </value>
            <value>
                <fullName>Avales</fullName>
            </value>
            <value>
                <fullName>Boletas de garantía</fullName>
            </value>
            <value>
                <fullName>Títulos y valores</fullName>
            </value>
            <value>
                <fullName>Cupones</fullName>
            </value>
            <value>
                <fullName>Tarjetas Nominadas</fullName>
            </value>
            <value>
                <fullName>Tarjetas Innominadas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFactory.cls
public class DataFactory {
    
    private static final String USER_FIRST_NAME = 'TestUser';
    private static final String USER_LAST_NAME = 'TestLastName';
    private static final String USER_EMAIL = 'user.email@test.com';
    
    public static User createUser(String profileName, Boolean doInsert) {
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;

        UserRole userrole = [   SELECT  Id, DeveloperName 
                                FROM    UserRole 
                                WHERE   DeveloperName = 'Presidente' Limit 1   ];

        Profile profile = [ SELECT  Id 
                            FROM    Profile 
                            WHERE   Name =: profileName 
                            LIMIT 1 ];

        User user = new User(
            firstName = USER_FIRST_NAME,
            lastName = USER_LAST_NAME,
            UserRoleId = userRole.Id,
            profileId = profile.id,
            username = USER_EMAIL,
            email = USER_EMAIL,
            EmailEncodingKey = 'ISO-8859-1',
            Alias = uniqueName.substring(18, 23),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US'
        );

        if(doInsert) {
            insert user;
        }
        return user;
    }
    
    public static Account insertAccount(){
        User adminUser = [  SELECT  Id, UserRoleId 
                            FROM    User 
                            WHERE   (Profile.Name='Administrador del sistema' or  Profile.Name='System Administrator') and IsActive = true
                            LIMIT 1 ];

        Account acc = new Account();
        acc.Name = 'Account Test';
        acc.OwnerId = adminUser.Id;
        insert acc;
        return acc;
    }
    
    public static Contact insertContact(Account acc){
        Contact contc = new Contact();
        contc.FirstName = 'FistName Test';
        contc.LastName = 'LastName Test';
        contc.AccountId = acc.Id;
        contc.Email = 'test@test.com';
        insert contc;
        return contc;
    }
    
    public static FS_ProductoAdquirido__c insertProduct(Account acc, String prod, String mod, String subM){
        FS_ProductoAdquirido__c p = new FS_ProductoAdquirido__c();
        p.FS_Cuenta__c = acc.Id;
        p.FS_Producto__c = prod;
        p.FS_Modulo__c = mod;
        p.FS_SubModulo__c = subM;
        p.FS_Esta_activo__c = true;
        insert p;
        return p;
    }
    
    public static Case insertCase(Account acc, Contact cont, FS_ProductoAdquirido__c p, String tipoRegistro){
        Case caso = new Case();
        caso.AccountId = acc.Id;
        caso.ContactId = cont.Id;
        caso.FS_Producto__c = p.FS_Producto__c;
        caso.FS_Modulo__c = p.FS_Modulo__c;
        caso.FS_SubModulo__c = p.FS_SubModulo__c;
        caso.FS_DescripcionCliente__c = '<p>Test</p>';
        caso.FS_TipoIncidente__c = 'Puntual';
        caso.FS_AgenteQA__c = userInfo.getUserId();
        caso.FS_AgenteN2__c = userInfo.getUserId();
        caso.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(tipoRegistro).getRecordTypeId();
        insert caso;
        return caso;
    }
    
    public static User insertUserCommunity(Contact cont){

        UserRole userrole = [   SELECT  Id, DeveloperName 
                                FROM    UserRole 
                                WHERE   DeveloperName = 'Presidente' Limit 1   ];

        User adminUser = [  SELECT  Id, UserRoleId 
                            FROM    User 
                            WHERE   (Profile.Name='Administrador del sistema' or  Profile.Name='System Administrator') and IsActive = true
                            LIMIT 1 ];

        adminUser.UserRoleId = userRole.Id;
        
        try {
        update adminUser;
        } catch (Exception e) {
           System.debug('An error occurred');
        }     

        User u = new User();

        System.runAs(adminUser) {
            u.Alias = 'tes'; 
            u.Email='test@myorg.com'; 
            u.EmailEncodingKey='UTF-8'; 
            u.LastName='Testing'; 
            u.LanguageLocaleKey='en_US'; 
            u.ContactId = cont.Id;
            u.LocaleSidKey='en_US'; 
            u.ProfileId = [Select Id from Profile Where Name = 'Customer Community User' or Name = 'Customer Community Plus User' limit 1].Id;
            u.TimeZoneSidKey='America/New_York';
            u.UserName= 'test@myorg.com';
            insert u;
        }
        return u;
    }
    
}