force-app/main/default/objects/Case/fields/FS_AceptaRespuesta__c.field-meta.xml
<CustomField>
    <fullName>FS_AceptaRespuesta__c</fullName>
    <label>Acepta Respuesta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FS_ValoresSiNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FS_Consulta.recordType-meta.xml
<RecordType>
    <fullName>FS_Consulta</fullName>
    <active>true</active>
    <businessProcess>FS_Casos</businessProcess>
    <label>Consulta</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Clientes.recordType-meta.xml
<RecordType>
    <fullName>Clientes</fullName>
    <active>true</active>
    <label>Clientes</label>
</RecordType>

force-app/main/default/objects/FS_ProductoAdquirido__c/FS_ProductoAdquirido__c.object-meta.xml
<CustomObject>
    <label>Producto Adquirido</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Nombre de Categoría</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos Adquiridos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/FS_ValoresSiNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Si</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Valores Si No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ControladorEncuesta_Test.cls
@isTest
public class ControladorEncuesta_Test {
    
    @TestSetup
    static void setup(){
        Account acc = DataFactory.insertAccount();
        Contact cont = DataFactory.insertContact(acc);
        FS_ProductoAdquirido__c p = DataFactory.insertProduct(acc, 'FISA System', 'Núcleo del Sistema', 'Parametros Generales (Módulo 1)');
        DataFactory.insertCase(acc, cont, p, 'FS_Consulta');
        DataFactory.insertProduct(acc, 'FISA System', 'Núcleo del Sistema', 'Clientes (Módulo 2)');
    }

    @isTest
    static void ControladorEncuesta() {
        Case caso =  [Select Id, RecordType.DeveloperName, ContactId from Case Where RecordTypeId = :CaseTriggerHelper.CONSULTA_TIPO_REGISTRO];
        Test.startTest();
        caso.FS_AceptaRespuesta__c = 'Si';
        update caso;
        ControladorEncuesta.actualizarCaso(JSON.serialize(ControladorEncuesta.getCaso(caso.Id, 'Muy Insatisfecho')));
        Test.stopTest();
    }

}