force-app/main/default/objects/Case/fields/FS_Acepta_Propuesta_Economica__c.field-meta.xml
<CustomField>
    <fullName>FS_Acepta_Propuesta_Economica__c</fullName>
    <label>Acepta Propuesta Económica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_AceptaRespuesta__c.field-meta.xml
<CustomField>
    <fullName>FS_AceptaRespuesta__c</fullName>
    <label>Acepta Respuesta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FS_ValoresSiNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Aplica_Licencia_Recurrente__c.field-meta.xml
<CustomField>
    <fullName>FS_Aplica_Licencia_Recurrente__c</fullName>
    <label>¿Aplica Licencia Recurrente?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Calificacion__c.field-meta.xml
<CustomField>
    <fullName>FS_Calificacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Calificación</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Cuando_Aplica_LR__c.field-meta.xml
<CustomField>
    <fullName>FS_Cuando_Aplica_LR__c</fullName>
    <label>¿Cuándo Aplica LR?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entrega de Solución</fullName>
            </value>
            <value>
                <fullName>Pase de Producción</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Dias_que_Aplica_LR__c.field-meta.xml
<CustomField>
    <fullName>FS_Dias_que_Aplica_LR__c</fullName>
    <label>Días que Aplica LR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Fecha_Puesta_en_Produccion__c.field-meta.xml
<CustomField>
    <fullName>FS_Fecha_Puesta_en_Produccion__c</fullName>
    <label>Fecha Puesta en Producción</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Quiere_Finalizar_la_Atencion_del_Caso__c.field-meta.xml
<CustomField>
    <fullName>FS_Quiere_Finalizar_la_Atencion_del_Caso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Quiere Finalizar la Atención del Caso?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FS_Requerimiento.recordType-meta.xml
<RecordType>
    <fullName>FS_Requerimiento</fullName>
    <active>true</active>
    <businessProcess>FS_Requerimiento</businessProcess>
    <label>Requerimiento</label>
</RecordType>

force-app/main/default/objects/FS_ProductoAdquirido__c/FS_ProductoAdquirido__c.object-meta.xml
<CustomObject>
    <label>Producto Adquirido</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Nombre de Categoría</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos Adquiridos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/FS_ValoresSiNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Si</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Valores Si No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TaskTriggerHelperTest.cls
/**
**************************************************************************************************************
* @author           Intellect Systems href=<infor@intellectsystems.net>
* @project          Fisa Ecuador - Implementación CRM
* @name             TaskTriggerHelperTest
* @description      Test class to TaskTrigger, TaskTriggerHandler and TaskTriggerHelper
* @changes
* ----------   ---------------------------   -----------------------------------------------------------------
* Date         Author                        Description
* ----------   ---------------------------   -----------------------------------------------------------------
* 2024-02-20   Intellect Systems             Initial version.
**************************************************************************************************************
*/

@IsTest
public class TaskTriggerHelperTest {
    
    private static final String REQUERIMIENTO_TIPO_REGISTRO = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('FS_Requerimiento').getRecordTypeId();
    
    /**
     * @method      setupTestData
     * @description Method that generates the test data used in test methods
     * @author      Intellect Systems - 2024-02-20
     */
	@TestSetup
    static void setupTestData(){ 
        Account acc = DataFactory.insertAccount();
        Contact cont = DataFactory.insertContact(acc);
        User user = DataFactory.createUser('PM-PS', true);
        FS_ProductoAdquirido__c p = DataFactory.insertProduct(acc, 'FISA System', 'Núcleo del Sistema', '');
        DataFactory.insertCase(acc, cont, p, 'FS_Requerimiento');
    }
    
	/**
     * @method      upsertTask
     * @description Method to create and prevent modify task record.
     * @author      Intellect Systems - 2024-02-20
     */
    @isTest
    static void upsertTask() {        
        List<Case> casosRequerimiento =  [	SELECT	Id, Status, OwnerId, ContactId, RecordType.DeveloperName, FS_Calificacion__c, FS_Aplica_Licencia_Recurrente__c, FS_Cuando_Aplica_LR__c, FS_Dias_que_Aplica_LR__c, FS_Acepta_Propuesta_Economica__c, FS_AceptaRespuesta__c, FS_Fecha_Puesta_en_Produccion__c, FS_Quiere_Finalizar_la_Atencion_del_Caso__c  
                                            FROM 	Case 
                                            WHERE	RecordTypeId =: REQUERIMIENTO_TIPO_REGISTRO];
        
        
        
        User user = [Select Id From User Where Profile.Name = 'PM-PS' and IsActive = true Limit 1];
        
        System.runAs(user) {
            
            Test.StartTest();
			Task tarea = new Task();
            tarea.WhatId = casosRequerimiento[0].Id;
            tarea.Subject = 'Test Task';
            tarea.TaskSubType = 'Email'; 
                
            insert tarea;
            
            try {
                tarea.Subject = 'Test Task Modify';
                update tarea;
            } catch(Exception ex) {
                System.debug(ex.getMessage());
            } 
            Test.StopTest();
        }    
	}  
}