force-app/main/default/objects/Case/fields/FS_AgenteN2__c.field-meta.xml
<CustomField>
    <fullName>FS_AgenteN2__c</fullName>
    <label>Agente N2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_AgenteQA__c.field-meta.xml
<CustomField>
    <fullName>FS_AgenteQA__c</fullName>
    <label>Agente QA</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_NombreTipoRegistro__c.field-meta.xml
<CustomField>
    <fullName>FS_NombreTipoRegistro__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Tipo de Registro</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SubEstado__c.field-meta.xml
<CustomField>
    <fullName>FS_SubEstado__c</fullName>
    <label>Sub Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apertura de caso</fullName>
                <default>true</default>
                <label>Apertura de caso</label>
            </value>
            <value>
                <fullName>Entrega 1a respuesta</fullName>
            </value>
            <value>
                <fullName>Análisis N1</fullName>
            </value>
            <value>
                <fullName>Aprobación Consulta N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solicitud N2</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Definitivo</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Puntual</fullName>
            </value>
            <value>
                <fullName>Revisión Documentación N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución IP-N2</fullName>
            </value>
            <value>
                <fullName>Aprobación de Solución IP-Release</fullName>
            </value>
            <value>
                <fullName>Costo Aceptado</fullName>
            </value>
            <value>
                <fullName>Costo Rechazado</fullName>
            </value>
            <value>
                <fullName>Análisis Falla Operativa</fullName>
            </value>
            <value>
                <fullName>Escalado a N2</fullName>
            </value>
            <value>
                <fullName>Análisis N2</fullName>
            </value>
            <value>
                <fullName>Envío de respuesta</fullName>
            </value>
            <value>
                <fullName>Respuesta aceptada</fullName>
            </value>
            <value>
                <fullName>Respuesta rechazada</fullName>
            </value>
            <value>
                <fullName>En reproceso por rechazo</fullName>
            </value>
            <value>
                <fullName>En Espera de Respuesta del Cliente</fullName>
            </value>
            <value>
                <fullName>Elaboración Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Aprobación Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Validación-Entrega de Fuentes</fullName>
            </value>
            <value>
                <fullName>Elaboración Solución Definitiva</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva Releases</fullName>
            </value>
            <value>
                <fullName>Escalado a QA</fullName>
            </value>
            <value>
                <fullName>Elaboración Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Aprobación Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Instalación Parche Releases</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrabajoAgenteHelper.cls
/**
**************************************************************************************************************
* @author           Intellect Systems href=<infor@intellectsystems.net>
* @project          Fisa Ecuador - Implementación CRM
* @name             TrabajoAgenteHelper
* @description      Assign cases to service queue
* @changes
* ----------   ---------------------------   -----------------------------------------------------------------
* Date         Author                        Description
* ----------   ---------------------------   -----------------------------------------------------------------
* 2023-07-20   Intellect Systems             Initial version.
* 2024-24-03   Intellect Systems             Call Method removed: CaseTriggerHelper.borrarChatter, after reviewing that they are unnecessary.
**************************************************************************************************************
*/

public without sharing class TrabajoAgenteHelper {

    public static void verificacionCaso(List<AgentWork> newAgentWork){
        List<String> recordIds = new List<String>();
        List<String> listUserId = new  List<String>();
        List<String> listUser = new  List<String>();
        List<Case> listCasosActualizar = new List<Case>();
        
        for(AgentWork item: newAgentWork){
            recordIds.add(item.WorkItemId);
            listUserId.add(item.UserId);
        }
        String query = 'Select ';
        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Case').getDescribe().fields.getMap();
        for(Schema.SObjectField sfield : fieldMap.Values()){
            schema.describefieldresult dfield = sfield.getDescribe();
            query += dfield.getname() + ',';
        }
        query = query.substring(0, query.length() - 1) + ' from Case Where Id in :recordIds';
        List<Case> listCasos = DataBase.query(query);
        for(User item :[Select Id from User Where Id in :listUserId ]){
            listUser.add(item.Id);
        }
        List<String> colasAtencion = new List<String>();
        for(Group item: [Select Id,Developername from Group Where DeveloperName Like '%FS_%' and Type = 'Queue']){
            colasAtencion.add(item.Id);
        }
        for(Case item: listCasos){
            for(AgentWork aw: newAgentWork){
                System.debug(colasAtencion.contains(aw.OriginalQueueId));
                System.debug(colasAtencion + ' ---- ' +aw.OriginalQueueId);
                if(item.Id == aw.WorkItemId && listUser.contains(aw.UserId) && colasAtencion.contains(aw.OriginalQueueId)){
                    listCasosActualizar.add(asignarcaso(item));
                }
            }
        }
        update listCasosActualizar;
    }
    
    public static Case asignarCaso(Case item){
        if(item.FS_SubEstado__c == 'Apertura de caso'){
            item.FS_SubEstado__c = 'Entrega 1a respuesta';
            CaseTriggerHelper.envioCorreo(item, 'FS_AsignacionCaso', true);
        }else if(item.FS_SubEstado__c == 'Escalado a N2'){
            item.FS_SubEstado__c = item.FS_NombreTipoRegistro__c == 'Incidente' ? 'Revisión Documentación N2' : 'Análisis N2';
            item.FS_AgenteN2__c = userInfo.getUserId();
            item.IsEscalated = true;
        }else if(item.FS_SubEstado__c == 'Escalado a QA'){
            item.FS_SubEstado__c = 'Elaboración Plan de Pruebas';
            item.FS_AgenteQA__c = userInfo.getUserId();
        } 
        return item;
    }
}