force-app/main/default/objects/Case/fields/FS_Correos_Notificaciones_PS__c.field-meta.xml
<CustomField>
    <fullName>FS_Correos_Notificaciones_PS__c</fullName>
    <label>Correos Notificaciones PS</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_CorreosNotificacionesServicios__c.field-meta.xml
<CustomField>
    <fullName>FS_CorreosNotificacionesServicios__c</fullName>
    <label>Correos Notificaciones Servicios</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_InformacionCompleta__c.field-meta.xml
<CustomField>
    <fullName>FS_InformacionCompleta__c</fullName>
    <label>Información Completa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
                <default>true</default>
                <label>Si</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_NombreContacto__c.field-meta.xml
<CustomField>
    <fullName>FS_NombreContacto__c</fullName>
    <formula>Contact.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Contacto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_NombreCuenta__c.field-meta.xml
<CustomField>
    <fullName>FS_NombreCuenta__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Cuenta</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_NombrePropietario__c.field-meta.xml
<CustomField>
    <fullName>FS_NombrePropietario__c</fullName>
    <formula>Owner:User.FirstName &amp; &apos; &apos; &amp; Owner:User.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Notificaciones__c.field-meta.xml
<CustomField>
    <fullName>FS_Notificaciones__c</fullName>
    <label>Notificaciones</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Estimación Macro</fullName>
            </value>
            <value>
                <fullName>Documento de Especificación Funcional</fullName>
            </value>
            <value>
                <fullName>En Propuesta Económica</fullName>
            </value>
            <value>
                <fullName>En Espera de Respuesta del Cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_OrigenCaso__c.field-meta.xml
<CustomField>
    <fullName>FS_OrigenCaso__c</fullName>
    <label>Origen del Caso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interno</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <default>true</default>
                <label>Web</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SubEstado__c.field-meta.xml
<CustomField>
    <fullName>FS_SubEstado__c</fullName>
    <label>Sub Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apertura de caso</fullName>
                <default>true</default>
                <label>Apertura de caso</label>
            </value>
            <value>
                <fullName>Entrega 1a respuesta</fullName>
            </value>
            <value>
                <fullName>Análisis N1</fullName>
            </value>
            <value>
                <fullName>Aprobación Consulta N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solicitud N2</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Definitivo</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Puntual</fullName>
            </value>
            <value>
                <fullName>Revisión Documentación N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución IP-N2</fullName>
            </value>
            <value>
                <fullName>Aprobación de Solución IP-Release</fullName>
            </value>
            <value>
                <fullName>Costo Aceptado</fullName>
            </value>
            <value>
                <fullName>Costo Rechazado</fullName>
            </value>
            <value>
                <fullName>Análisis Falla Operativa</fullName>
            </value>
            <value>
                <fullName>Escalado a N2</fullName>
            </value>
            <value>
                <fullName>Análisis N2</fullName>
            </value>
            <value>
                <fullName>Envío de respuesta</fullName>
            </value>
            <value>
                <fullName>Respuesta aceptada</fullName>
            </value>
            <value>
                <fullName>Respuesta rechazada</fullName>
            </value>
            <value>
                <fullName>En reproceso por rechazo</fullName>
            </value>
            <value>
                <fullName>En Espera de Respuesta del Cliente</fullName>
            </value>
            <value>
                <fullName>Elaboración Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Aprobación Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Validación-Entrega de Fuentes</fullName>
            </value>
            <value>
                <fullName>Elaboración Solución Definitiva</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva Releases</fullName>
            </value>
            <value>
                <fullName>Escalado a QA</fullName>
            </value>
            <value>
                <fullName>Elaboración Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Aprobación Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Instalación Parche Releases</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SubEstadoQueSePideInformacion__c.field-meta.xml
<CustomField>
    <fullName>FS_SubEstadoQueSePideInformacion__c</fullName>
    <label>Sub Estado que se Pide Información</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FS_Requerimiento.recordType-meta.xml
<RecordType>
    <fullName>FS_Requerimiento</fullName>
    <active>true</active>
    <businessProcess>FS_Requerimiento</businessProcess>
    <label>Requerimiento</label>
</RecordType>

force-app/main/default/classes/FeedCommentTriggerHelper.cls
/**
**************************************************************************************************************
* @author           Intellect Systems href=<infor@intellectsystems.net>
* @project          Fisa Ecuador - Implementación CRM
* @name             FeedCommentTriggerHelper
* @description      Class to validate permission to FeedComment and Send Notifications
* @changes
* ----------   ---------------------------   -----------------------------------------------------------------
* Date         Author                        Description
* ----------   ---------------------------   -----------------------------------------------------------------
* 2023-08-23   Intellect Systems             Initial version.
**************************************************************************************************************
*/

public without sharing class FeedCommentTriggerHelper {

    /**
     * @method      validacionComentario
     * @description Update case info related to chatter feed comment
     * @author      Intellect Systems - 2023-08-23
     * @param       newFeedCommentList
     */
    public static void validacionComentario(List<FeedComment> newFeedCommentList){
        List<String> listFeedItemIds = new List<String>();
        List<String> listCasosIds = new List<String>();
        List<Case> listCasosUpdate = new List<Case>();

        for(Profile p: [    SELECT  Id 
                            FROM    Profile 
                            WHERE   (Name = 'Customer Community User' or Name = 'Customer Community Plus User') and Id =:UserInfo.getProfileId()    ]){
            for(FeedComment item: newFeedCommentList){
                listFeedItemids.add(item.FeedItemId);
            } 
        }

        for(FeedItem item: [    SELECT  ParentId 
                                FROM    FeedItem 
                                WHERE   Id in :listFeedItemids    ]){
            listCasosIds.add(item.ParentId);
        }
        
        for(Case item: [    SELECT  FS_SubEstado__c, FS_SubEstadoQueSePideInformacion__c, FS_InformacionCompleta__c 
                            FROM    Case 
                            WHERE   Id IN : listCasosIds and FS_SubEstadoQueSePideInformacion__c != null    ]){
            item.FS_SubEstado__c = item.FS_SubEstadoQueSePideInformacion__c;
            item.FS_SubEstadoQueSePideInformacion__c = null;
            item.FS_InformacionCompleta__c = null;
            listCasosUpdate.add(item);
        }

        update listCasosUpdate;
        
    }
    
    /**
     * @method      validacionModificacion
     * @description Validate permissions to delete record
     * @author      Intellect Systems - 2023-08-23
     * @param       newFeedCommentList
     */
    public static void validacionModificacion(List<FeedComment> newFeedCommentList){
        if(FeedItemTriggerHelper.validacionUser() || System.isFuture()){
            return;
        }
        for(FeedComment item: newFeedCommentList){
            item.addError('Privilegios insuficiente');
        } 
    }

    /**
     * @method      sendNotification
     * @description Send Email when Communty User send a chatter message
     * @author      Intellect Systems - 2024-01-31
     * @param       records
     */
    public static void sendNotification(List<FeedComment> records) {
        Set<Id> idCases = new Set<Id>();
        for(FeedComment record : records) {
            idCases.add(record.ParentId);
        }

        Case caseRecord = [     SELECT  Id, CaseNumber, OwnerId, RecordTypeId , RecordType.DeveloperName, Status, Subject, CreatedDate, Description, FS_NombrePropietario__c, FS_NombreCuenta__c , FS_OrigenCaso__c, FS_NombreContacto__c, ContactId, FS_CorreosNotificacionesServicios__c, FS_Correos_Notificaciones_PS__c, FS_Notificaciones__c 
                                FROM    Case 
                                WHERE   Id IN : idCases    ];
                            
        //Validate case status
        if(caseRecord.Status == 'Cerrado' || caseRecord.Status == 'Pendiente de Respuesta CSAT' || caseRecord.Status == 'Dado de Baja') {
            for(FeedComment record : records) {
                record.addError('No puede añadir nuevos comentarios en el estado actual del caso');
            }    
        } 
        
        //Consult case history 
        if(caseRecord.Status == 'En Espera de Respuesta del Cliente') {
            if(!Test.isRunningTest()) {
            CaseHistory caseHistory = [     SELECT      Id, CaseId, Field, NewValue, OldValue, CreatedDate 
                                            FROM        CaseHistory 
                                            WHERE       CaseId =: caseRecord.Id and Field = 'Status' 
                                            ORDER BY    CreatedDate Desc 
                                            LIMIT       1    ];
            }    

            //Returning the case to the previous state when the client writes in the chatter
            if(caseHistory.Id != null || Test.isRunningTest()) {
                caseRecord.Status = String.valueOf(caseHistory.OldValue);
                try {
                    update caseRecord;    
                } catch (Exception ex) {
                    System.debug('Error generado desde FeedCommentTriggerHelper: '+ ex.getLineNumber() + '**' + +ex.getMessage());
                }
            }
        }

        if(caseRecord.RecordType.DeveloperName == 'FS_Requerimiento') {
            CaseTriggerHelper.envioCorreo(caseRecord, 'FS_Cliente_Aprueba_Notificacion', false);
        }
    }

}