force-app/main/default/objects/Case/fields/FS_NombreTipoRegistro__c.field-meta.xml
<CustomField>
    <fullName>FS_NombreTipoRegistro__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Tipo de Registro</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SubEstado__c.field-meta.xml
<CustomField>
    <fullName>FS_SubEstado__c</fullName>
    <label>Sub Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apertura de caso</fullName>
                <default>true</default>
                <label>Apertura de caso</label>
            </value>
            <value>
                <fullName>Entrega 1a respuesta</fullName>
            </value>
            <value>
                <fullName>Análisis N1</fullName>
            </value>
            <value>
                <fullName>Aprobación Consulta N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solicitud N2</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Definitivo</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Puntual</fullName>
            </value>
            <value>
                <fullName>Revisión Documentación N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución IP-N2</fullName>
            </value>
            <value>
                <fullName>Aprobación de Solución IP-Release</fullName>
            </value>
            <value>
                <fullName>Costo Aceptado</fullName>
            </value>
            <value>
                <fullName>Costo Rechazado</fullName>
            </value>
            <value>
                <fullName>Análisis Falla Operativa</fullName>
            </value>
            <value>
                <fullName>Escalado a N2</fullName>
            </value>
            <value>
                <fullName>Análisis N2</fullName>
            </value>
            <value>
                <fullName>Envío de respuesta</fullName>
            </value>
            <value>
                <fullName>Respuesta aceptada</fullName>
            </value>
            <value>
                <fullName>Respuesta rechazada</fullName>
            </value>
            <value>
                <fullName>En reproceso por rechazo</fullName>
            </value>
            <value>
                <fullName>En Espera de Respuesta del Cliente</fullName>
            </value>
            <value>
                <fullName>Elaboración Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Aprobación Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Validación-Entrega de Fuentes</fullName>
            </value>
            <value>
                <fullName>Elaboración Solución Definitiva</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva Releases</fullName>
            </value>
            <value>
                <fullName>Escalado a QA</fullName>
            </value>
            <value>
                <fullName>Elaboración Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Aprobación Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Instalación Parche Releases</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_TipoIncidente__c.field-meta.xml
<CustomField>
    <fullName>FS_TipoIncidente__c</fullName>
    <label>Tipo de Incidente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Puntual</fullName>
            </value>
            <value>
                <fullName>Definitivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ConfiguracionSLA__c/FS_ConfiguracionSLA__c.object-meta.xml
<CustomObject>
    <label>configuración SLA</label>
    <nameField>
        <displayFormat>SLA-{0000}</displayFormat>
        <label>No SLA</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuraciones SLA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_ConfiguracionSLA__c/fields/FS_Activo__c.field-meta.xml
<CustomField>
    <fullName>FS_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_ConfiguracionSLA__c/fields/FS_EsCliente__c.field-meta.xml
<CustomField>
    <fullName>FS_EsCliente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Es cliente?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_ConfiguracionSLA__c/fields/FS_NombreDeCuenta__c.field-meta.xml
<CustomField>
    <fullName>FS_NombreDeCuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre de la Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Configuraciones SLA</relationshipLabel>
    <relationshipName>Configuraciones_SLA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_ConfiguracionSLA__c/fields/FS_NombreTipoRegistro__c.field-meta.xml
<CustomField>
    <fullName>FS_NombreTipoRegistro__c</fullName>
    <label>Nombre Tipo de Registro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consulta</fullName>
            </value>
            <value>
                <fullName>Incidente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ConfiguracionSLA__c/fields/FS_SLA__c.field-meta.xml
<CustomField>
    <fullName>FS_SLA__c</fullName>
    <inlineHelpText>Se añade el tiempo estimado en horas para que se ejecute la respuesta del cliente e interno.</inlineHelpText>
    <label>SLA (Horas Laborales)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_ConfiguracionSLA__c/fields/FS_SubEstado__c.field-meta.xml
<CustomField>
    <fullName>FS_SubEstado__c</fullName>
    <label>Sub Estado</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apertura de caso</fullName>
            </value>
            <value>
                <fullName>Entrega 1a respuesta</fullName>
            </value>
            <value>
                <fullName>Información validada</fullName>
            </value>
            <value>
                <fullName>Análisis N1</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Definitivo</fullName>
            </value>
            <value>
                <fullName>Revisión Documentación N2</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Puntual</fullName>
            </value>
            <value>
                <fullName>Aprobación de Solución IP-Release</fullName>
            </value>
            <value>
                <fullName>Costo Aceptado</fullName>
            </value>
            <value>
                <fullName>Costo Rechazado</fullName>
            </value>
            <value>
                <fullName>Análisis Falla Operativa</fullName>
            </value>
            <value>
                <fullName>Escalado a N2</fullName>
            </value>
            <value>
                <fullName>Análisis N2</fullName>
            </value>
            <value>
                <fullName>Envío de respuesta</fullName>
            </value>
            <value>
                <fullName>Respuesta aceptada</fullName>
            </value>
            <value>
                <fullName>Respuesta rechazada</fullName>
            </value>
            <value>
                <fullName>En reproceso por rechazo</fullName>
            </value>
            <value>
                <fullName>En Espera de Respuesta del Cliente</fullName>
            </value>
            <value>
                <fullName>Elaboración Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Aprobación Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Validación-Entrega de Fuentes</fullName>
            </value>
            <value>
                <fullName>Elaboración Solución Definitiva</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva Releases</fullName>
            </value>
            <value>
                <fullName>Escalado a QA</fullName>
            </value>
            <value>
                <fullName>Elaboración Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Aprobación Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Instalación Parche Releases</fullName>
            </value>
            <value>
                <fullName>Aprobación Instalación Parche - Releases</fullName>
            </value>
            <value>
                <fullName>Certificación Parche QA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ConfiguracionSLA__c/fields/FS_Tipo_de_Incidente__c.field-meta.xml
<CustomField>
    <fullName>FS_Tipo_de_Incidente__c</fullName>
    <label>Tipo de Incidente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Puntual</fullName>
            </value>
            <value>
                <fullName>Definitivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MilestoneCalculator.cls
global class MilestoneCalculator implements Support.MilestoneTriggerTimeCalculator {
    global Integer calculateMilestoneTriggerTime(String caseId, String milestoneTypeId){
        integer timerSLA;
        String recordTypeName;
        String subEstado;
        String accId;
        String TipoIncidente;
        set<String> milestoneNames = new set <String>();
        List<FS_ConfiguracionSLA__c> slaLs = new List<FS_ConfiguracionSLA__c>();
        list<case> caseList = new list<case>();
        //recuperamos el caso del que se busca SLA. 
        caseList = [SELECT Priority, RecordType.Name, FS_SubEstado__c, AccountId, FS_TipoIncidente__c FROM Case WHERE Id=:caseId];
        //Case c = [SELECT Priority, RecordType.Name, FS_SubEstado__c, AccountId, FS_TipoIncidente__c FROM Case WHERE Id=:caseId];
        
        for(Case lstCase : caseList){
            recordTypeName = lstCase.RecordType.Name;
            accId = lstCase.AccountId;
            subEstado = lstCase.FS_SubEstado__c;
            TipoIncidente = lstCase.FS_TipoIncidente__c;
        } System.debug('Datos SLA: '+recordTypeName+'--'+accId+'-'+subEstado+'-'+TipoIncidente);
        //buscamos la configuracion de sla dependiendo del tipo de registro, nombre de cuenta y sub estado.
        slaLs = [select id, FS_NombreDeCuenta__c, FS_NombreTipoRegistro__c, FS_SLA__c, FS_SubEstado__c, FS_EsCliente__c, 
                 FS_Activo__c from FS_ConfiguracionSLA__c where FS_Activo__c = true AND FS_NombreTipoRegistro__c =: recordTypeName
                 AND FS_NombreDeCuenta__c =: accId AND FS_SubEstado__c INCLUDES(:subEstado) AND FS_Tipo_de_Incidente__c =: TipoIncidente limit 1];
        System.debug('slaLs es: '+slaLs);
        for(FS_ConfiguracionSLA__c lstSLA: slaLs){
            //asignamos el SLA correspondiente convirtiendo el valor de horas a minutos.
            timerSLA = integer.ValueOf(lstSLA.FS_SLA__c) * 60;
            system.debug('SLA actualizado' + timerSLA);
        }
        return timerSLA;
    }
}