force-app/main/default/objects/Preguntas_de_Encuesta__c/Preguntas_de_Encuesta__c.object-meta.xml
<CustomObject>
    <label>Preguntas de Encuesta</label>
    <nameField>
        <label>Preguntas de Encuesta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preguntas de Encuesta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Preguntas_de_Encuesta__c/fields/Pregunta_de_encuestra__c.field-meta.xml
<CustomField>
    <fullName>Pregunta_de_encuestra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pregunta de encuestra</label>
    <referenceTo>SurveyQuestion</referenceTo>
    <relationshipLabel>Preguntas de Encuesta</relationshipLabel>
    <relationshipName>Preguntas_de_Encuesta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Preguntas_de_Encuesta__c/fields/Version_de_Encuesta__c.field-meta.xml
<CustomField>
    <fullName>Version_de_Encuesta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Versión de Encuesta</label>
    <referenceTo>SurveyVersion</referenceTo>
    <relationshipLabel>Preguntas de Encuesta</relationshipLabel>
    <relationshipName>Preguntas_de_Encuesta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SurveyQuestionFlow.cls
/**
**************************************************************************************************************
* @author           Intellect Systems href=<info@intellectsystems.net>
* @project          Fisa Ecuador - Implementación CRM
* @name             SurveyQuestionFlow
* @description       Invocable class to create a duplicate record of SurveyQuestion standard object in preguntas_de_encuestas__c custom object.
* @changes
* ----------   ---------------------------   -----------------------------------------------------------------
* Date         Author                        Description
* ----------   ---------------------------   -----------------------------------------------------------------
* 2024-06-26   Intellect Systems             Initial version.
**************************************************************************************************************
*/
public class SurveyQuestionFlow {
    
    /**
     * @method      createClone
     * @description Method to create a clone from SurveyQuestion to Preguntas_de_Encuesta__c object 
     * @author      Intellect Systems - 2024-06-26
     * @param       records - SurveyQuestion List 
     */
    @InvocableMethod
    public static void createClone(List<String> values) {
        
        List<SurveyQuestion> records = new List<SurveyQuestion>();
        records = [	SELECT	Id, SurveyVersionId 
                   	FROM	SurveyQuestion
                  	WHERE Id In: values];
        
        List<Preguntas_de_Encuesta__c> questionsList = new List<Preguntas_de_Encuesta__c>();
        for(SurveyQuestion record : records) {
        	Preguntas_de_Encuesta__c question = new Preguntas_de_Encuesta__c();
            question.Pregunta_de_encuestra__c = record.Id;
            question.Version_de_Encuesta__c = record.SurveyVersionId;
            questionsList.add(question);
        }
        
        if(!questionsList.isEmpty()) {
        	insert questionsList;
        }
    }

}