force-app/main/default/objects/FS_Gestor_Cuenta__c/FS_Gestor_Cuenta__c.object-meta.xml
<CustomObject>
    <label>Gestor Cuenta</label>
    <nameField>
        <label>Nombre de Gestor Cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gestor Cuentas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Gestor_Cuenta__c/fields/FS_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>FS_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Gestor Cuentas</relationshipLabel>
    <relationshipName>Gestor_Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Gestor_Cuenta__c/fields/FS_Principal__c.field-meta.xml
<CustomField>
    <fullName>FS_Principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Gestor_Cuenta__c/fields/FS_Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>FS_Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gestor_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GestorCuentaTriggerHelper.cls
public without sharing class GestorCuentaTriggerHelper { 
    
    public static void validatePrincipal(List<FS_Gestor_Cuenta__c> records) {
        Set<Id> listGestorCuenta = new Set<Id>();
        for(FS_Gestor_Cuenta__c newRecord : records) {
            listGestorCuenta.add(newRecord.FS_Cuenta__c);	    
        }    
        
        Map<String, FS_Gestor_Cuenta__c> searchRecords = new Map<String, FS_Gestor_Cuenta__c>([    SELECT  Id, FS_Cuenta__c, FS_Project_Manager__c, FS_Principal__c 
                                                                                                FROM    FS_Gestor_Cuenta__c 
                                                                                                WHERE   FS_Cuenta__c IN : listGestorCuenta and FS_Principal__c = true    ]);

        if(!searchRecords.isEmpty()) {
            for(FS_Gestor_Cuenta__c newRecord : records) {               
                for (Id key : searchRecords.keySet()) {
                    if(searchRecords.get(key).FS_Principal__c == newRecord.FS_Principal__c) {
                        newRecord.addError('Ya existe un registro marcado como el Project Manager principal.');	    
                    }
                }  	    
            }            
        }    
    }
    
    public static void validatePrincipalUpdate(List<FS_Gestor_Cuenta__c> records,  Map<Id, FS_Gestor_Cuenta__c> oldRecords) {
        Set<Id> listGestorCuenta = new Set<Id>();
        for(FS_Gestor_Cuenta__c newRecord : records) {
            listGestorCuenta.add(newRecord.FS_Cuenta__c);	    
        }    
        
        Map<String, FS_Gestor_Cuenta__c> searchRecords = new Map<String, FS_Gestor_Cuenta__c>([    SELECT  Id, FS_Cuenta__c, FS_Project_Manager__c, FS_Principal__c 
                                                                                                FROM    FS_Gestor_Cuenta__c 
                                                                                                WHERE   FS_Cuenta__c IN : listGestorCuenta and FS_Principal__c = true    ]);

        if(!searchRecords.isEmpty()) {
            for(FS_Gestor_Cuenta__c newRecord : records) {               
                for (Id key : searchRecords.keySet()) {
                    if(searchRecords.get(key).FS_Principal__c == newRecord.FS_Principal__c && newRecord.FS_Project_Manager__c == oldRecords.get(newRecord.Id).FS_Project_Manager__c) {
                    	newRecord.addError('Ya existe un registro marcado como el Project Manager principal.');	    
                    }
                }  	    
            }            
        }    
    }
}