force-app/main/default/objects/FS_ProductoAdquirido__c/FS_ProductoAdquirido__c.object-meta.xml
<CustomObject>
    <label>Producto Adquirido</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Nombre de Categoría</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos Adquiridos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>FS_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos Adquiridos</relationshipLabel>
    <relationshipName>ProductosAdquiridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Esta_activo__c.field-meta.xml
<CustomField>
    <fullName>FS_Esta_activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Está activo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProductsPurchasedTriggerHelper_Test.cls
@isTest
public class ProductsPurchasedTriggerHelper_Test {   
	@TestSetup
    static void setup(){ 
        Account acc = DataFactory.insertAccount();
        Contact cont = DataFactory.insertContact(acc);
        DataFactory.insertProduct(acc, 'FISA System', 'Núcleo del Sistema', 'Seguridades (Modulo 90)');
        DataFactory.insertProduct(acc, 'FISA CreditCard', '', '');
        DataFactory.insertProduct(acc, 'OMNIA', '', '');
        DataFactory.insertProduct(acc, 'FISA FISS', '', '');
        
    }
    
    @isTest
    static void updateProduct() {
        Account accRecord = [Select Id, Name From Account Where Name = 'Account Test'];
    	FS_ProductoAdquirido__c product =  [	SELECT	Id, Name, FS_Esta_activo__c 
                                            	FROM	FS_ProductoAdquirido__c 
                                            	WHERE	FS_Cuenta__c =: accRecord.Id
                                           		LIMIT	1]; 
        
        product.FS_Esta_activo__c = false;
        product.FS_Esta_activo__c = true;
        update product;
        delete product;
    }
}