force-app/main/default/objects/Contact/fields/FS_KAM__c.field-meta.xml
<CustomField>
    <fullName>FS_KAM__c</fullName>
    <label>KAM</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_PMCore__c.field-meta.xml
<CustomField>
    <fullName>FS_PMCore__c</fullName>
    <label>PM Core</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_PMOmnia__c.field-meta.xml
<CustomField>
    <fullName>FS_PMOmnia__c</fullName>
    <label>PM Omnia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_PMPSPrincipal__c.field-meta.xml
<CustomField>
    <fullName>FS_PMPSPrincipal__c</fullName>
    <label>PM-PS Principal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_PMPSSecundario__c.field-meta.xml
<CustomField>
    <fullName>FS_PMPSSecundario__c</fullName>
    <label>PM-PS Secundario</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Producto_1__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto_1__c</fullName>
    <label>Producto 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Producto_2__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto_2__c</fullName>
    <label>Producto 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Producto_3__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto_3__c</fullName>
    <label>Producto 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Producto_4__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto_4__c</fullName>
    <label>Producto 4</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Gestor_Cuenta__c/FS_Gestor_Cuenta__c.object-meta.xml
<CustomObject>
    <label>Gestor Cuenta</label>
    <nameField>
        <label>Nombre de Gestor Cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gestor Cuentas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Gestor_Cuenta__c/fields/FS_Area__c.field-meta.xml
<CustomField>
    <fullName>FS_Area__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Omnia</fullName>
            </value>
            <value>
                <fullName>PM-PS</fullName>
            </value>
            <value>
                <fullName>KAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Gestor_Cuenta__c/fields/FS_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>FS_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Gestor Cuentas</relationshipLabel>
    <relationshipName>Gestor_Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Gestor_Cuenta__c/fields/FS_Principal__c.field-meta.xml
<CustomField>
    <fullName>FS_Principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Gestor_Cuenta__c/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA CreditCard</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
            <value>
                <fullName>FISA FISS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Gestor_Cuenta__c/fields/FS_Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>FS_Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gestor_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/FS_ProductoAdquirido__c.object-meta.xml
<CustomObject>
    <label>Producto Adquirido</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Nombre de Categoría</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos Adquiridos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>FS_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos Adquiridos</relationshipLabel>
    <relationshipName>ProductosAdquiridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Esta_activo__c.field-meta.xml
<CustomField>
    <fullName>FS_Esta_activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Está activo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Modulo__c.field-meta.xml
<CustomField>
    <fullName>FS_Modulo__c</fullName>
    <label>Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Producto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Núcleo del Sistema</fullName>
            </value>
            <value>
                <fullName>Cajas y Bóveda (Módulo 3)</fullName>
            </value>
            <value>
                <fullName>Captaciones a la Vista (Módulo 4)</fullName>
            </value>
            <value>
                <fullName>Captaciones a Plazo (Módulo 5)</fullName>
            </value>
            <value>
                <fullName>Colocaciones (Módulo 6)</fullName>
            </value>
            <value>
                <fullName>Comercio Exterior (Módulo 10)</fullName>
            </value>
            <value>
                <fullName>Tesorería (Módulo 12)</fullName>
            </value>
            <value>
                <fullName>Tarjeta de Débito (Módulo 15)</fullName>
            </value>
            <value>
                <fullName>DIPS (Modulo 19)</fullName>
            </value>
            <value>
                <fullName>Contabilidad (Módulo 20)</fullName>
            </value>
            <value>
                <fullName>Reportes (Módulo 21)</fullName>
            </value>
            <value>
                <fullName>Garantías (Módulo 28)</fullName>
            </value>
            <value>
                <fullName>Calendarizador Procesos Bach</fullName>
            </value>
            <value>
                <fullName>Core Tarjeta de Crédito</fullName>
            </value>
            <value>
                <fullName>MCM (MultiChannel Managemt)</fullName>
            </value>
            <value>
                <fullName>Business Application Generator</fullName>
            </value>
            <value>
                <fullName>Business Support Aplication</fullName>
            </value>
            <value>
                <fullName>BRE (Motor de reglas)</fullName>
            </value>
            <value>
                <fullName>Business Application Products (Plataforma de Ventas)</fullName>
            </value>
            <value>
                <fullName>BackOffice</fullName>
            </value>
            <value>
                <fullName>Online Banking Personas</fullName>
            </value>
            <value>
                <fullName>Mobile Banking Personas</fullName>
            </value>
            <value>
                <fullName>Kioskos</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Rapid Cash</fullName>
            </value>
            <value>
                <fullName>DIPS</fullName>
            </value>
            <value>
                <fullName>ECCO</fullName>
            </value>
            <value>
                <fullName>IMS</fullName>
            </value>
            <value>
                <fullName>Flujos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA CreditCard</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
            <value>
                <fullName>FISA FISS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_SubModulo__c.field-meta.xml
<CustomField>
    <fullName>FS_SubModulo__c</fullName>
    <label>Sub Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Modulo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clientes (Módulo 2)</fullName>
            </value>
            <value>
                <fullName>Parametros Generales (Módulo 1)</fullName>
            </value>
            <value>
                <fullName>Seguridades (Modulo 90)</fullName>
            </value>
            <value>
                <fullName>Cuentas de Ahorro</fullName>
            </value>
            <value>
                <fullName>Cuentas Corrientes</fullName>
            </value>
            <value>
                <fullName>Cuentas de Acumulación</fullName>
            </value>
            <value>
                <fullName>Cuentas Nostro</fullName>
            </value>
            <value>
                <fullName>Cuentas Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Depositos a Plazo Fijo</fullName>
            </value>
            <value>
                <fullName>Créditos de Consumo/Comerciales/Personales</fullName>
            </value>
            <value>
                <fullName>Crédito Automotriz</fullName>
            </value>
            <value>
                <fullName>Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario con Letras</fullName>
            </value>
            <value>
                <fullName>Cartas de crédito</fullName>
            </value>
            <value>
                <fullName>Cobranzas</fullName>
            </value>
            <value>
                <fullName>Avales</fullName>
            </value>
            <value>
                <fullName>Boletas de garantía</fullName>
            </value>
            <value>
                <fullName>Títulos y valores</fullName>
            </value>
            <value>
                <fullName>Cupones</fullName>
            </value>
            <value>
                <fullName>Tarjetas Nominadas</fullName>
            </value>
            <value>
                <fullName>Tarjetas Innominadas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTriggerHelper.cls
/**
**************************************************************************************************************
* @author           Intellect Systems href=<info@intellectsystems.net>
* @project          Fisa Ecuador - Implementación CRM
* @name             ContactTriggerHelper
* @description      Helper to ContactTriggerHandler class.
* @changes
* ----------   ---------------------------   -----------------------------------------------------------------
* Date         Author                        Description
* ----------   ---------------------------   -----------------------------------------------------------------
* 2024-05-24   Intellect Systems             Initial version.
**************************************************************************************************************
*/

public without sharing class ContactTriggerHelper {
    
    /**
     * @method      assignProducts
     * @description Method to fill values in FS_Productos__c contact field 
     * @author      Intellect Systems - 2024-05-24
     * @param       records - Contact List 
     */
    public static void assignProducts(List<Contact> records) {
        Set<Id> accountsIds = new Set<Id>();
    	//Get AccountId
        for(Contact record : records) {
        	accountsIds.add(record.AccountId);
        }

        //Search related Products
        Map<Id, FS_ProductoAdquirido__c> productsList = new Map<Id, FS_ProductoAdquirido__c>([	SELECT	Id, FS_Cuenta__c, FS_Producto__c, FS_Modulo__c, FS_SubModulo__c, FS_Esta_activo__c
                                               													FROM	FS_ProductoAdquirido__c
                                               													WHERE	FS_Cuenta__c IN: accountsIds	]);
        
         //Search related Manager
        Map<Id, FS_Gestor_Cuenta__c> managerList = new Map<Id, FS_Gestor_Cuenta__c>([	SELECT	Id, FS_Cuenta__c, FS_Principal__c, FS_Area__c, FS_Project_Manager__r.name
                                               													FROM	FS_Gestor_Cuenta__c
                                               													WHERE	FS_Cuenta__c IN: accountsIds	]);

        //Find all active related products
        Set<String> listAllProducts = new Set<String>();
        for(Id key : productsList.keySet()) {
            Id accountId = productsList.get(key).FS_Cuenta__c;
            if(productsList.get(key).FS_Esta_activo__c == true && accountId == productsList.get(key).FS_Cuenta__c) {
                listAllProducts.add(productsList.get(key).FS_Producto__c);
            }    
        }
        
        //Find all active related Manager
        Set<String> listAllManager = new Set<String>();
        for(Id keyManager : managerList.keySet()) {
            Id accountId = managerList.get(keyManager).FS_Cuenta__c;
            if(accountId == managerList.get(keyManager).FS_Cuenta__c) {
           		//valida si el gestor es el pm-ps principal.
           		for(Contact record : records) {
                	if(managerList.get(keyManager).FS_Principal__c == true && managerList.get(keyManager).FS_Area__c == 'PM-PS'){
                    	record.FS_PMPSPrincipal__c = managerList.get(keyManager).FS_Project_Manager__r.name;
                	}
                	//valida si el gestor es el pm-ps.
                	if(managerList.get(keyManager).FS_Principal__c == false && managerList.get(keyManager).FS_Area__c == 'PM-PS'){
                    	record.FS_PMPSSecundario__c = managerList.get(keyManager).FS_Project_Manager__r.name;
                	}
                	//valida si el gestor es el PM-Core.
                	if(managerList.get(keyManager).FS_Principal__c == false && managerList.get(keyManager).FS_Area__c == 'Core'){
                    	record.FS_PMCore__c = managerList.get(keyManager).FS_Project_Manager__r.name;
                	}
                	//valida si el gestor es el PM-Omnia.
                	if(managerList.get(keyManager).FS_Principal__c == false && managerList.get(keyManager).FS_Area__c == 'Omnia'){
                    	record.FS_PMOmnia__c = managerList.get(keyManager).FS_Project_Manager__r.name;
                	}
                	//valida si el gestor es el PM-KAM.
                	if(managerList.get(keyManager).FS_Principal__c == false && managerList.get(keyManager).FS_Area__c == 'KAM'){
                    	record.FS_KAM__c = managerList.get(keyManager).FS_Project_Manager__r.name; 
                	}
                }

            }    
        }

        //Update products in contact
        if(!productsList.IsEmpty()) {
        	for(Contact record : records) {
                if(listAllProducts.contains('FISA System')){
                    record.FS_Producto_1__c = 'FISA System';
                }
                if(listAllProducts.contains('FISA CreditCard')){
                     record.FS_Producto_2__c = 'FISA CreditCard';
                }
                if(listAllProducts.contains('OMNIA')){
                     record.FS_Producto_3__c = 'OMNIA';
                }
                if(listAllProducts.contains('FISA FISS')){
                     record.FS_Producto_4__c = 'FISA FISS';
                }
                //record.FS_Productos__c = String.join(listAllProducts, ';' );
            }	   
        }
        
        
    }
}