force-app/main/default/objects/Contact/fields/FS_Producto_1__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto_1__c</fullName>
    <label>Producto 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Producto_2__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto_2__c</fullName>
    <label>Producto 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Producto_3__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto_3__c</fullName>
    <label>Producto 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Producto_4__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto_4__c</fullName>
    <label>Producto 4</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/FS_ProductoAdquirido__c.object-meta.xml
<CustomObject>
    <label>Producto Adquirido</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Nombre de Categoría</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos Adquiridos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>FS_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos Adquiridos</relationshipLabel>
    <relationshipName>ProductosAdquiridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Esta_activo__c.field-meta.xml
<CustomField>
    <fullName>FS_Esta_activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Está activo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Modulo__c.field-meta.xml
<CustomField>
    <fullName>FS_Modulo__c</fullName>
    <label>Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Producto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Núcleo del Sistema</fullName>
            </value>
            <value>
                <fullName>Cajas y Bóveda (Módulo 3)</fullName>
            </value>
            <value>
                <fullName>Captaciones a la Vista (Módulo 4)</fullName>
            </value>
            <value>
                <fullName>Captaciones a Plazo (Módulo 5)</fullName>
            </value>
            <value>
                <fullName>Colocaciones (Módulo 6)</fullName>
            </value>
            <value>
                <fullName>Comercio Exterior (Módulo 10)</fullName>
            </value>
            <value>
                <fullName>Tesorería (Módulo 12)</fullName>
            </value>
            <value>
                <fullName>Tarjeta de Débito (Módulo 15)</fullName>
            </value>
            <value>
                <fullName>DIPS (Modulo 19)</fullName>
            </value>
            <value>
                <fullName>Contabilidad (Módulo 20)</fullName>
            </value>
            <value>
                <fullName>Reportes (Módulo 21)</fullName>
            </value>
            <value>
                <fullName>Garantías (Módulo 28)</fullName>
            </value>
            <value>
                <fullName>Calendarizador Procesos Bach</fullName>
            </value>
            <value>
                <fullName>Core Tarjeta de Crédito</fullName>
            </value>
            <value>
                <fullName>MCM (MultiChannel Managemt)</fullName>
            </value>
            <value>
                <fullName>Business Application Generator</fullName>
            </value>
            <value>
                <fullName>Business Support Aplication</fullName>
            </value>
            <value>
                <fullName>BRE (Motor de reglas)</fullName>
            </value>
            <value>
                <fullName>Business Application Products (Plataforma de Ventas)</fullName>
            </value>
            <value>
                <fullName>BackOffice</fullName>
            </value>
            <value>
                <fullName>Online Banking Personas</fullName>
            </value>
            <value>
                <fullName>Mobile Banking Personas</fullName>
            </value>
            <value>
                <fullName>Kioskos</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Rapid Cash</fullName>
            </value>
            <value>
                <fullName>DIPS</fullName>
            </value>
            <value>
                <fullName>ECCO</fullName>
            </value>
            <value>
                <fullName>IMS</fullName>
            </value>
            <value>
                <fullName>Flujos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA CreditCard</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
            <value>
                <fullName>FISA FISS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_SubModulo__c.field-meta.xml
<CustomField>
    <fullName>FS_SubModulo__c</fullName>
    <label>Sub Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Modulo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clientes (Módulo 2)</fullName>
            </value>
            <value>
                <fullName>Parametros Generales (Módulo 1)</fullName>
            </value>
            <value>
                <fullName>Seguridades (Modulo 90)</fullName>
            </value>
            <value>
                <fullName>Cuentas de Ahorro</fullName>
            </value>
            <value>
                <fullName>Cuentas Corrientes</fullName>
            </value>
            <value>
                <fullName>Cuentas de Acumulación</fullName>
            </value>
            <value>
                <fullName>Cuentas Nostro</fullName>
            </value>
            <value>
                <fullName>Cuentas Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Depositos a Plazo Fijo</fullName>
            </value>
            <value>
                <fullName>Créditos de Consumo/Comerciales/Personales</fullName>
            </value>
            <value>
                <fullName>Crédito Automotriz</fullName>
            </value>
            <value>
                <fullName>Líneas de Crédito</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario</fullName>
            </value>
            <value>
                <fullName>Crédito Hipotecario con Letras</fullName>
            </value>
            <value>
                <fullName>Cartas de crédito</fullName>
            </value>
            <value>
                <fullName>Cobranzas</fullName>
            </value>
            <value>
                <fullName>Avales</fullName>
            </value>
            <value>
                <fullName>Boletas de garantía</fullName>
            </value>
            <value>
                <fullName>Títulos y valores</fullName>
            </value>
            <value>
                <fullName>Cupones</fullName>
            </value>
            <value>
                <fullName>Tarjetas Nominadas</fullName>
            </value>
            <value>
                <fullName>Tarjetas Innominadas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductsPurchasedTriggerHelper.cls
/**
**************************************************************************************************************
* @author           Intellect Systems href=<info@intellectsystems.net>
* @project          Fisa Ecuador - Implementación CRM
* @name             ProductsPurchasedTriggerHelper
* @description      Helper to ProductsPurchasedTriggerHandler class.
* @changes
* ----------   ---------------------------   -----------------------------------------------------------------
* Date         Author                        Description
* ----------   ---------------------------   -----------------------------------------------------------------
* 2024-05-27   Intellect Systems             Initial version.
**************************************************************************************************************
*/

public without sharing class ProductsPurchasedTriggerHelper {
    
	/**
     * @method      assignProducts
     * @description Method to assign related products to contact field 
     * @author      Intellect Systems - 2024-05-27
     * @param       records - FS_ProductoAdquirido__c List
     */
    
    
    public static void assignProducts(List<FS_ProductoAdquirido__c> records) {
        Set<Id> accountsIds = new Set<Id>();
    	//Get AccountId
        for(FS_ProductoAdquirido__c record : records) {
        	accountsIds.add(record.FS_Cuenta__c);
        }
        //Search related Contacts
        Map<Id, Contact> contactsList = new Map<Id, Contact>([	SELECT	Id, Name, AccountId, FS_Productos__c, FS_Producto_1__c,
                                                                FS_Producto_2__c, FS_Producto_3__c, FS_Producto_4__c
                                               					FROM	Contact
                                               					WHERE	AccountId IN: accountsIds	]);
        
        //Search related Products
        Map<Id, FS_ProductoAdquirido__c> productsList = new Map<Id, FS_ProductoAdquirido__c>([	SELECT	Id, FS_Cuenta__c, FS_Producto__c, FS_Modulo__c, FS_SubModulo__c, FS_Esta_activo__c
                                               													FROM	FS_ProductoAdquirido__c
                                               													WHERE	FS_Cuenta__c IN: accountsIds	]);
        
        //Assign all active related ProductsPurchased to Contact
        Set<String> listAllProducts = new Set<String>();
        
        for(Id keyProduct : productsList.keySet()) {
            Id accountId = productsList.get(keyProduct).FS_Cuenta__c;
            
            
            if(productsList.get(keyProduct).FS_Esta_activo__c == true && accountId == productsList.get(keyProduct).FS_Cuenta__c ) {
                listAllProducts.add(productsList.get(keyProduct).FS_Producto__c);
                //listAllProducts1.add(productsList.get(keyProduct).FS_Producto__c);
                //&& productsList.get(keyProduct).FS_Producto__c == 'FISA System'
                for(Id keyContact : contactsList.keySet()) {
                    if(contactsList.get(keyContact).AccountId == productsList.get(keyProduct).FS_Cuenta__c) {
                        //contactsList.get(keyContact).FS_Producto_1__c = 'FISA System';
                        if(listAllProducts.contains('FISA System')){
                            contactsList.get(keyContact).FS_Producto_1__c = 'FISA System';
                        }else{
                            contactsList.get(keyContact).FS_Producto_1__c = '';
                        }
                        
                        if(listAllProducts.contains('FISA CreditCard')){
                            contactsList.get(keyContact).FS_Producto_2__c = 'FISA CreditCard';
                        }else{
                            contactsList.get(keyContact).FS_Producto_2__c = '';
                        }
                        
                        if(listAllProducts.contains('OMNIA')){
                            contactsList.get(keyContact).FS_Producto_3__c = 'OMNIA';
                        }else{
                            contactsList.get(keyContact).FS_Producto_3__c = '';
                        }
                        
                        if(listAllProducts.contains('FISA FISS')){
                            contactsList.get(keyContact).FS_Producto_4__c = 'FISA FISS';
                        }else{
                            contactsList.get(keyContact).FS_Producto_4__c = '';
                        }
                    	//contactsList.get(keyContact).FS_Productos__c = String.join(listAllProducts, ';' );	   
                    }    
                }
            }   
            
             
        }//fin for
        if(contactsList.size() > 0) {
        	update contactsList.values();}
        
        
        
    }
    
    public static void deleteProducts(List<FS_ProductoAdquirido__c> oldRecords){
        
    
        Set<Id> accountsIds = new Set<Id>();
    	//Get AccountId
        for(FS_ProductoAdquirido__c record : oldRecords) {
        	accountsIds.add(record.FS_Cuenta__c);
        }
        //Search related Contacts
        Map<Id, Contact> contactsList = new Map<Id, Contact>([	SELECT	Id, Name, AccountId, FS_Productos__c, FS_Producto_1__c,
                                                                FS_Producto_2__c, FS_Producto_3__c, FS_Producto_4__c
                                               					FROM	Contact
                                               					WHERE	AccountId IN: accountsIds	]);
        
        //Search related Products
        Map<Id, FS_ProductoAdquirido__c> productsList = new Map<Id, FS_ProductoAdquirido__c>([	SELECT	Id, FS_Cuenta__c, FS_Producto__c, FS_Modulo__c, FS_SubModulo__c, FS_Esta_activo__c
                                               													FROM	FS_ProductoAdquirido__c
                                               													WHERE	FS_Cuenta__c IN: accountsIds and Id IN:	oldRecords ALL ROWS]);
        
        //Assign all active related ProductsPurchased to Contact
        Set<String> listAllProducts = new Set<String>();
        
        for(Id keyProduct : productsList.keySet()) {
            Id accountId = productsList.get(keyProduct).FS_Cuenta__c;

            if(productsList.get(keyProduct).FS_Esta_activo__c == true && accountId == productsList.get(keyProduct).FS_Cuenta__c ) {
                listAllProducts.add(productsList.get(keyProduct).FS_Producto__c);
                for(Id keyContact : contactsList.keySet()) {
                    if(contactsList.get(keyContact).AccountId == productsList.get(keyProduct).FS_Cuenta__c) {
                        
                        if(listAllProducts.contains('FISA System')){
                            contactsList.get(keyContact).FS_Producto_1__c = '';
                        }
                        
                        if(listAllProducts.contains('FISA CreditCard')){
                            contactsList.get(keyContact).FS_Producto_2__c = '';
                        }
                        
                        if(listAllProducts.contains('OMNIA')){
                            contactsList.get(keyContact).FS_Producto_3__c = '';
                        }
                        
                        if(listAllProducts.contains('FISA FISS')){
                            contactsList.get(keyContact).FS_Producto_4__c = '';
                        }
                    }
                }
            }
        }
        
        if(contactsList.size() > 0) {
        	update contactsList.values();}

    }
    
}